export const SET_DISPLAY_MENU_BAR = 'SET_DISPLAY_MENU_BAR';
export const SET_DISPLAY_FILTERS = 'SET_DISPLAY_FILTERS';
export const INITIAL_COUNTRIES = 'INITIAL_COUNTRIES';
export const RENDER_COUNTRIES = 'RENDER_COUNTRIES';